### ISSUE TITLE
Doesnt save settings

### ISSUE THREAD

**Issue by ghost** [ClassZ/FriendGroups#2]
Such as class colour and hide offline dont save on relog

**Comment by Mikeprod** [comment]
I solved it today because it was bothering me too. 
You can find the solution in my forked repo : https://github.com/Mikeprod/FriendGroups

**Comment by ClassZ** [comment]
Sorry for not be able to do it...and thank Mikeprod for doing it. I haven't be able to play the game as frequent as I was,
And I also just merged your pull request.
