### ISSUE TITLE
Layout Breaks

### ISSUE THREAD

**Issue by kaykaykay2** [ClassZ/FriendGroups#5]
Hello,
since Legion i cant use FriendGroups anymore the Groups kinda Break out of Line as u can see on this Picture http://oi64.tinypic.com/w2djco.jpg

i cant open the Grps It just Went from + to - but doesnt Shows the Groups and who is in it sometimes after Opening more Groups it Shows People but not in Order and with some Graphic Glitches and than i need to close anything and after that cant Look in the Groups again...
would be so nice if u could have a Look at it your Addon is the only Usefull Addon to Order your Flist which is so Helpfull to Order Random Raids,Randoms,Pvp etc pp would Love to keep using it

Greetings

**Comment by Mikeprod** [comment]
Can you acknowledge that there is nothing wrong with my version [here](https://github.com/Mikeprod/FriendGroups/)

**Comment by kaykaykay2** [comment]
i will test it as soon i can.. its 7pm here so iam off to party but when i
get home i test it directly..

thanks for that anyhow really missing that addon :)

2016-11-05 18:12 GMT+01:00 Mikeprod notifications@github.com:

**Comment by kaykaykay2** [comment]
Yep as far i could see its Working like it should! very nice thank you

2016-11-05 18:59 GMT+01:00 daniel breissner kay4everrrr@googlemail.com:
