### ISSUE TITLE
[7.1] Needs compatching to work

### ISSUE THREAD

**Issue by zeress** [ClassZ/FriendGroups#6]
7.1 seems to have broken the friends tab for this add-on. Probably related to the quick join tab that was added

**Comment by hymccord** [comment]
I'm working on a patch but it's not a quick fix. A lot of changes happened to the FriendsFrame.lua.

**Comment by Mikeprod** [comment]
I'll work on it today and see what I can do about that

**Comment by Mikeprod** [comment]
I have a working thing locally, but it's fucked up with the limited 11 buttons/scrolling page ... I don't know how it was smooth before .... Moreover I have a tooltip on a group that was not handled the same way before. A lot of work has indeed to be done to make it work ;) And I agree with @InKahootz a lot of changes happened in the FriendFrames.lua

**Comment by dblanch369** [comment]
If you need someone to help test it, count me in.

**Comment by ghost** [comment]
dotn forget to change version number in .toc to 71000 or higher

**Comment by dblanch369** [comment]
Any luck?

**Comment by Mikeprod** [comment]
I have been busy working on another addon ... I'll look into it later this week. Maybe meanwhile @InKahootz has better luck fixing it ?

**Comment by hymccord** [comment]
I'm working my way through it. Lots of changes coupled with a code base I'm unfamiliar with makes for slow going. The 9-5 and Legion also takes a lot of my time and I'm going to Blizzcon so it'll be a bit. Soon 
™.

**Comment by Mikeprod** [comment]
Ok maybe I'll have something working at the end of the week

**Comment by Mikeprod** [comment]
Well I worked on it today, I fixed all tooltip problems. I have display/scrolling problems to fix.

Edit : Tell me if you want me to push my work on my fork.

**Comment by dblanch369** [comment]
Please!  I can give it a try and get you some feedback.

**Comment by Mikeprod** [comment]
Well, I realised I commented a line, fixing the trouble I had with the display XD However scrolling is not as smooth as before I'll be fixing that before pull request ;) Here is my [repo](https://github.com/Mikeprod/FriendGroups)

**Comment by Mikeprod** [comment]
It's all good at this hour. I created my pull request ! Enjoy the fully working addon ;)

**Comment by Mikeprod** [comment]
If @ClassZ wants to give me credit for this update ;)

**Comment by dblanch369** [comment]
I found a bug, do you want me to post here, or make a new ticket?

**Comment by Mikeprod** [comment]
I don't know ... post it here ...

**Comment by dblanch369** [comment]
Now that I think of it, I believe this was an issue in the 7.0.3 one as well, but I don't recall seeing a LUA error back then... When you filter the list by selecting "Hide All Offline", the list will continue to scroll even after the last visible person is shown, and each 'scroll tick' the error is logged.  Perhaps when that option is selected, you have to recalculate the number of entries to scroll to?  Just wondering..  When that option is not selected, the scroll works as expected and did not generate a LUA error.

Here's the log entry that happens...

52x SharedXML\HybridScrollFrame.lua:188: bad argument #1 to 'floor' (number expected, got nil)
[C]: in function `floor'
SharedXML\HybridScrollFrame.lua:188: in function`HybridScrollFrame_SetOffset'
SharedXML\HybridScrollFrame.lua:30: in function <SharedXML\HybridScrollFrame.lua:29>
[C]: in function `SetValue'
SharedXML\HybridScrollFrame.lua:67: in function <SharedXML\HybridScrollFrame.lua:57>

Locals:
(_temporary) = nil
(_temporary) = "number expected, got nil"

**Comment by Mikeprod** [comment]
Can you acknowledge that the error happens only when the list is scrolled all the way down ?

**Comment by Mikeprod** [comment]
That's what I get and it appears to come from the blizzard UI script

> 1x SharedXML\HybridScrollFrame.lua:188: bad argument #1 to 'floor' (number expected, got nil)
> [C]: in function `floor'
> SharedXML\HybridScrollFrame.lua:188: in function`HybridScrollFrame_SetOffset'
> SharedXML\HybridScrollFrame.lua:30: in function <SharedXML\HybridScrollFrame.lua:29>
> [C]: in function `SetValue'
> SharedXML\HybridScrollFrame.lua:104: in function`HybridScrollFrame_Update'
> FrameXML\FriendsFrame.lua:1309: in function `FriendsFrame_UpdateFriends'
> FrameXML\FriendsFrame.lua:610: in function <FrameXML\FriendsFrame.lua:513>
> [C]: in function`FriendsList_Update'
> FrameXML\FriendsFrame.lua:903: in function `FriendsFrame_OnEvent'
> [string "_:OnEvent"]:1: in function <[string "_:OnEvent"]:1>
> 
> Locals:
> (_temporary) = nil
> (_temporary) = "number expected, got nil"

**Comment by Mikeprod** [comment]
I just pushed a fix. Could you please confirm that no error pops up anymore ?

**Comment by dblanch369** [comment]
Sorry for the delay.  No more LUA errors, yay!  Thank you for the update.  If I see anything else, I'll reply.

**Comment by zeress** [comment]
Hurray! Thanks for your hard work :)
